<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class MakersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('makers')->truncate();
        DB::table('makers')->insert([
            ['id' => 1,'name' => 'コーセー','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 2,'name' => 'ミヤリサン製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 6,'name' => 'J&J','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 7,'name' => 'オムロン','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 8,'name' => 'アース製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 9,'name' => '玉川衛材','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 10	,'name' => 'カネボウ化粧品','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 11,'name' => '常盤薬品','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 12,'name' => '大塚製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 13,'name' => 'エーザイ','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 14,'name' => '第一三共ヘルスケア','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 15,'name' => '興和株式会社','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 16,'name' => 'ロート製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 17,'name' => '小林製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 18,'name' => '資生堂','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 19,'name' => 'ユニチャーム','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 20,'name' => '大王製紙','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 21,'name' => 'ライオン','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 22,'name' => 'P&G','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 23,'name' => '花王','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 24,'name' => 'ジョンソン','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 25,'name' => '金鳥','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 26,'name' => '大正製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 27,'name' => 'エスエス製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 28,'name' => '明治','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 29,'name' => '佐藤製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 30,'name' => '武田薬品','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 31,'name' => 'クラシエ','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 32,'name' => '参天製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 33,'name' => 'ニチバン','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 34,'name' => 'アサヒグループ食品','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 35,'name' => '塩野義製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 36,'name' => '森永製菓','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 37,'name' => 'グラクソスミスクライン','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 38,'name' => 'ホーユー','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 39,'name' => 'カネボウ','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 40,'name' => 'DHC','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 41,'name' => 'ヘンケルジャパン','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 42,'name' => 'コカコーラ','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 43,'name' => 'タニタ','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 44,'name' => 'キューピー','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 45,'name' => 'ムネ製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 46,'name' => '久光製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 47,'name' => '大木製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 48,'name' => '味の素','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 49,'name' => 'ユニリーバ','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 50,'name' => 'バスクリン','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 51,'name' => 'キスミー','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 52,'name' => 'AMO','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 53,'name' => '日本アルコン','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 54,'name' => 'ゼリア新薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 55,'name' => 'フマキラー','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 56,'name' => 'ハマダコンフェックス','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 57,'name' => '牛乳石鹸','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 58,'name' => '池田模範堂','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 59,'name' => '湧永製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 60,'name' => 'メニコン','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 61,'name' => '共立薬品工業','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 62,'name' => 'クラシエ薬品','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 63,'name' => '江崎グリコ','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 64,'name' => '白十字','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 65,'name' => 'ハウス食品','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 66,'name' => '近江兄弟社','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 67,'name' => '井藤漢方製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 68,'name' => 'ジョンソン&ジョンソン','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 69,'name' => '白元','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 70,'name' => '大鵬薬品','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 71,'name' => 'ファンケル','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 72,'name' => 'テルモ','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 73,'name' => 'ツムラ','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 74,'name' => '資生堂薬品','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 75,'name' => '松浦薬業','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 76,'name' => 'シック','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 77,'name' => '貝印','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 78,'name' => 'サンスター','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 79,'name' => 'マンダム','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 80,'name' => 'ピップ','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 81,'name' => 'スリーエム','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 82,'name' => '森永乳業','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 84,'name' => 'ちふれ','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 85,'name' => 'ユウキ製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 86,'name' => 'ジェックス','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 87,'name' => '健栄製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 88,'name' => 'オカモト','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 89,'name' => 'UHA味覚糖','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 90,'name' => '山本漢方製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 91,'name' => 'レキットベンキーザ','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 92,'name' => 'エビス','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 93,'name' => 'ピジョン','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 94,'name' => '大幸薬品','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 95,'name' => '伊勢半','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 96,'name' => 'サナ','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 97,'name' => 'ナリス','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 98,'name' => '日本ヘルスケア製薬','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
            ['id' => 99,'name' => '伊藤忠商事','created_at' => Carbon::now(),'updated_at' => Carbon::now()],
        ]);
    }
}
